SiCentroAcopio:
  connection: doctrine
  tableName: si_centro_acopio
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: centro_acopio
    nombre:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: true
      primary: false
    rif:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: true
      primary: false
    telefono:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    email:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    ubicacion:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    coordenadas:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    id_sap:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    id_organizacion:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
  relations:
    SiSilos:
      local: id
      foreign: id_centro_acopio
      type: many
SiSilos:
  connection: doctrine
  tableName: si_silos
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: silos
    id_centro_acopio:
      type: integer(8)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    nombre:
      type: string(255)
      fixed: true
      unsigned: false
      notnull: true
      primary: false
    ubicacion:
      type: string(3)
      fixed: true
      unsigned: false
      notnull: false
      primary: false
  relations:
    SiCentroAcopio:
      local: id_centro_acopio
      foreign: id
      type: one
