<?php

/**
 * SiCentroAcopioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiCentroAcopioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiCentroAcopioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiCentroAcopio');
    }
}