<?php

/**
 * SiSilosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiSilosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiSilosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiSilos');
    }
}