<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SiCentroAcopio', 'doctrine');

/**
 * BaseSiCentroAcopio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $rif
 * @property string $telefono
 * @property string $email
 * @property string $ubicacion
 * @property string $coordenadas
 * @property string $id_sap
 * @property string $id_organizacion
 * @property Doctrine_Collection $SiSilos
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getRif()             Returns the current record's "rif" value
 * @method string              getTelefono()        Returns the current record's "telefono" value
 * @method string              getEmail()           Returns the current record's "email" value
 * @method string              getUbicacion()       Returns the current record's "ubicacion" value
 * @method string              getCoordenadas()     Returns the current record's "coordenadas" value
 * @method string              getIdSap()           Returns the current record's "id_sap" value
 * @method string              getIdOrganizacion()  Returns the current record's "id_organizacion" value
 * @method Doctrine_Collection getSiSilos()         Returns the current record's "SiSilos" collection
 * @method SiCentroAcopio      setId()              Sets the current record's "id" value
 * @method SiCentroAcopio      setNombre()          Sets the current record's "nombre" value
 * @method SiCentroAcopio      setRif()             Sets the current record's "rif" value
 * @method SiCentroAcopio      setTelefono()        Sets the current record's "telefono" value
 * @method SiCentroAcopio      setEmail()           Sets the current record's "email" value
 * @method SiCentroAcopio      setUbicacion()       Sets the current record's "ubicacion" value
 * @method SiCentroAcopio      setCoordenadas()     Sets the current record's "coordenadas" value
 * @method SiCentroAcopio      setIdSap()           Sets the current record's "id_sap" value
 * @method SiCentroAcopio      setIdOrganizacion()  Sets the current record's "id_organizacion" value
 * @method SiCentroAcopio      setSiSilos()         Sets the current record's "SiSilos" collection
 * 
 * @package    sigesi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiCentroAcopio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('si_centro_acopio');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'centro_acopio',
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('rif', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('ubicacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('coordenadas', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_sap', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_organizacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SiSilos', array(
             'local' => 'id',
             'foreign' => 'id_centro_acopio'));
    }
}