<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SiSilos', 'doctrine');

/**
 * BaseSiSilos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_centro_acopio
 * @property string $nombre
 * @property string $ubicacion
 * @property SiCentroAcopio $SiCentroAcopio
 * 
 * @method integer        getId()               Returns the current record's "id" value
 * @method integer        getIdCentroAcopio()   Returns the current record's "id_centro_acopio" value
 * @method string         getNombre()           Returns the current record's "nombre" value
 * @method string         getUbicacion()        Returns the current record's "ubicacion" value
 * @method SiCentroAcopio getSiCentroAcopio()   Returns the current record's "SiCentroAcopio" value
 * @method SiSilos        setId()               Sets the current record's "id" value
 * @method SiSilos        setIdCentroAcopio()   Sets the current record's "id_centro_acopio" value
 * @method SiSilos        setNombre()           Sets the current record's "nombre" value
 * @method SiSilos        setUbicacion()        Sets the current record's "ubicacion" value
 * @method SiSilos        setSiCentroAcopio()   Sets the current record's "SiCentroAcopio" value
 * 
 * @package    sigesi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiSilos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('si_silos');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'silos',
             'length' => 8,
             ));
        $this->hasColumn('id_centro_acopio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 255,
             ));
        $this->hasColumn('ubicacion', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiCentroAcopio', array(
             'local' => 'id_centro_acopio',
             'foreign' => 'id'));
    }
}